### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ndom91**
# Pull Request Template

## Description

My initial goal was to fix tests I noticed were failing in the last README PR, but then I also noticed that dependencies were pretty far out of date, so I decided to focus on bringing dependencies up to date first. Thats the goal of this PR.

## Type of change

Please delete options that are not relevant.

- Dependency Upgrade

## How Has This Been Tested?

Currently tests are running again at least, but of course some are still failing. Issues include:

- EventRecorder doesn't seem to boot or get attached to the window object correctly.
- There is one eslint error remaining from existing code, `no-prototype-builtins` in `src/code-generator/CodeGenerator.js:163`. Not sure if we've just been ignoring that or if it can/should be fixed. Maybe add a `/* eslint-disable-next-line */` ?

## Checklist:

- [ ] My code follows the style guidelines of this project. `npm run lint` passes with no errors.
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. `npm run test` passes with no errors.

### CODE REVIEW

**Comment by ndom91** [comment]
@ianaya89 hey whats up with this? All the babel stuff is upgraded to the latest versions, incl. pkg renames etc. Shuold I keep it open?

**Comment by ianaya89** [comment]
@ndom91  Is this ready to review? I never looked because is still as draft

**Comment by ndom91** [comment]
Yeah let me check this out tonight. I don't remember if its ready to merge yet or not, but I'd like to get the dependencies up-to-date. What do you think?

**Comment by ianaya89** [comment]
@ndom91 Yes, totally in favor of that. I am also thinking that is time to make "big" update in terms of tool and maybe worth it to create a new chrome app from zero (to keep stuff updated). Lets put this on hold for now. Will let you know later this week

**Comment by ndom91** [comment]
Not necessary anymore. Closing 👍

**Pull request closed without merging**
